# Derived data-plane dispatcher image with Conduktor Azure OAUTHBEARER handler
ARG BASE_IMAGE=gcr.io/knative-releases/knative-kafka-broker-dispatcher-loom@sha256:c0c6904f33d767d4c7255781085ebac2fbc72b88dc5f34d3588bb183bb825721
FROM ${BASE_IMAGE}

USER root
COPY conduktor-azure-oauthbearer.jar /app/libs/conduktor-azure-oauthbearer.jar
RUN echo ":/app/libs/conduktor-azure-oauthbearer.jar" >> /app/jib-classpath-file
USER 185
