# demo-frontend: external-facing UI
apiVersion: platform.acme.com/v1alpha1
kind: AcmeService
metadata:
  name: demo-frontend
  namespace: default
spec:
  template:
    containers:
      - name: frontend
        image: acrknativelab.azurecr.io/demo-frontend:latest
        ports:
          - containerPort: 80
  servicePort: 80
  serviceType: LoadBalancer
  scalingType: static
  ingress: true
  eventingSink: false
  eventingSource: false
  allowFrom: []
