apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: demo-backend-trigger
spec:
  broker: default
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: demo-backend
    uri: /
