# Allow frontend to reach Jupyter notebook
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-frontend-to-jupyter
  namespace: default
spec:
  podSelector:
    matchLabels:
      app: demo-jupyter
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: demo-frontend
      ports:
        - protocol: TCP
          port: 8888
